services:
  dashboard:
    image: mattwh/meshcore-dashboard:latest
    ports:
      - "8080:8080"
    volumes:
      # Persist data between updates
      - ./data/settings.json:/app/settings.json
      - ./data/repeater_history.db:/app/repeater_history.db
    restart: unless-stopped

  ntfy:
    image: binwiederhier/ntfy
    command: serve
    ports:
      - "2586:80"
    volumes:
      - ./data/ntfy:/var/cache/ntfy
    restart: unless-stopped
